# Generated by Django 2.0.9 on 2018-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='crawl_interval',
            field=models.IntegerField(default=10, verbose_name='Crawl Interval in minutes'),
        ),
    ]
