# Generated by Django 2.0.9 on 2018-12-07 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20181207_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
